### ISSUE TITLE
[ERROR] ExtWrenchesAndJointTorquesEstimator :: computeExpectedFTSensorsMeasurements : Error in estimating external wrenches and joint torques.

### ISSUE THREAD

**Issue by TeoKa** [robotology-playground/insitu-ft-analysis#3]
File Executed with the dataset: 2016_04_13
Run showing this error:

[ERROR] ExtWrenchesAndJointTorquesEstimator :: computeExpectedFTSensorsMeasurements : Error in estimating external wrenches and joint torques.

Matlab used:
MATLAB2015b
on:
Mac OS X 10.10.5

**Comment by traversaro** [comment]
I tested on my system, and with this modification to the param.m file : https://gitlab.com/dynamic-interaction-control/icub-insitu-ft-analysis-big-datasets/commit/6542012761c62445bdcab582884b3e201a98fdbb it is working correctly . 
I will check tomorrow on your laptop.

**Comment by traversaro** [comment]
@TeoKa I updated the level of verbosity of that class in case of error: https://github.com/robotology/idyntree/commit/ea653e4c925e94d26a4896cbe2ddae20349d1f08 . 
Can you update the superbuild ( https://github.com/robotology/codyco-superbuild#update ), restart matlab and retry? Thanks.

**Comment by traversaro** [comment]
I think we fixed this one.
