### ISSUE TITLE
iCubDarmstadt01 root_link not leveled, so datasets got until now on iCubDarmstadt01 until now are invalid

### ISSUE THREAD

**Issue by traversaro** [robotology-playground/insitu-ft-analysis#5]
We did the error in assessing that the root_link of the robot, when mounted on the fixed base that they have in iCubDarmstadt01, is actually leveled (i.e. the gravity is just on the z axis of the `root_link`). Then all the datasets that we collected, as they were collected with the robot mounted on the fixed base pole and in the analysis we assume that the gravity at the base is known to be (0,0,9.81) are **INVALID** (when used under that assumption). 

@fjandrad can you add a disclaimer on all the README of the Darmstadt datasets explaining this issue?

**Comment by traversaro** [comment]
cc @DanielePucci @francesco-romano @nunoguedelha 

@misaki43 that is definitly something that we need to write explicitly on your guide, as we missed this when we did the fine calibration!

**Comment by fjandrad** [comment]
@traversaro  I think we have only 2 datasets from darmstadt so far , is that correct? If that's the case I finished adding the disclaimers to all.

**Comment by traversaro** [comment]
Yep, there was just two datasets, thanks!
