### ISSUE TITLE
Save images of idyntree.visualizer to make video of the icub positions as well

### ISSUE THREAD

**Issue by fjandrad** [robotology-playground/insitu-ft-analysis#53]
use the function drawToFile from idyntree.visualizer to save a video matching the one of the forces when using the visualizeExperiment function.

**Comment by traversaro** [comment]
If you have ffmpeg installed, here https://gitlab.com/dynamic-interaction-control/icra-2016-reference-spreading/blob/master/VisualizationWithMeshes.m#L133 you can find some useful code.

**Comment by fjandrad** [comment]
Actually forgot to close the issue. Is solved in 3765f1a5351c80e4673add53f957a8be1132c1c2, by creating the image with drawToFile and then reading with imread , and using matlab video creating feature.
