### ISSUE TITLE
Octave tests are not running in Travis 

### ISSUE THREAD

**Issue by traversaro** [robotology-playground/insitu-ft-analysis#7]
It would be nice to get them to work again : https://travis-ci.org/robotology-playground/insitu-ft-analysis .

**Comment by fjandrad** [comment]
I have been trying for the last days to fix this since is really annoying. I even try to coment the test_on_utils stuff thinking it would not even check anything to no avail..

I have no idea how to fix this :-1:

**Comment by traversaro** [comment]
I checked a bit, and the error is invoked by:
* https://github.com/MOxUnit/MOxUnit/blob/2e57c916fd30e07c01f99a6b73044cdc60cdb2a3/MOxUnit/%40MOxUnitTestSuite/addFromFile.m#L32

I think that the problem is that MOxUnit expects every file of tests to define a matlab function. 
See on this MOxUnit docs https://github.com/MOxUnit/MOxUnit/blob/master/README.md#running-moxunit-tests and for an example the matlab tests of iDynTree https://github.com/robotology/idyntree/tree/master/bindings/matlab/tests. 

Converting the script to this format (and using the assert functions if the tests are not working properly) should fix the problem. Alternatively we can move the test to use any other method (I choose MOxUnit because unfortunately Octave does not support the Matlab unit test official library https://it.mathworks.com/help/matlab/matlab-unit-test-framework.html ).

**Comment by fjandrad** [comment]
Solved
