### ISSUE TITLE
Ft comparison Green iCub vs Purple iCub

### ISSUE THREAD

**Issue by fjandrad** [robotology-playground/insitu-ft-analysis#9]
#  **Results of  computeEllipsoidWithGridDataset.m**

##  Left leg

| --| Model  | X  | Y  | Z
| ------------- | ------------- | ------------- | ------------- | ------------- |
| Green Mass  | 4.738180  | 5.962046  | 8.851642  | 5.303845 |
| Purple Mass  | 4.738191  | 4.870861  | 6.666255  | 4.944546 |
|  |  |  |  |  |
| Green Mass no Smartfit | 4.738180  | 6.595553  | 9.326977  | 7.264902 |
| Purple Mass  no Smartfit | 4.738191  | 4.973491  | 6.668731  | 5.540870
|  |  |  |  |  |
| Green Force Error  | 0 | 12.006123  | 40.353067  | 5.549169 |
| Purple Force Error  |0  |1.301496  | 18.914310  | 2.024343 |
|  |  |  |  |  |
| Green Force no Smartfit  | 0 | 18.220826  | 45.016098  | 24.787141 |
| Purple Force no Smartfit  |0  | 2.308296  | 18.938602  | 7.874280 |

 **Remark: mass in kg and forces in N.**

_Symmetry among axis_

| Robot  | std (kg) | std no model (kg) |
| ------------- | ------------- | ------------- |
| Green  | 1.887232  | 1.423661 |
| Purple   | 1.015968  | 0.862924 |

## Right leg

| --| Model  | X  | Y  | Z
| ------------- | ------------- | ------------- | ------------- | ------------- |
| Green Mass  | 4.733288  | 5.227913  | 6.971536  | 4.942367 |
| Purple Mass  | 4.733281  | 4.081828  |6.089324  | 3.414204 |
|  |  |  |  |  |
| Green Mass no Smartfit | 4.733288  | 6.068035  | 7.488945  | 6.221753 |
| Purple Mass  no Smartfit | 4.733281  | 5.016673  | 6.454476  | 4.752116
|  |  |  |  |  |
| Green Force Error  | 0 | 4.852270  | 21.957204  | 2.051057 |
| Purple Force Error  |0   | -6.390757  | 13.302780  | -12.940147 |
|  |  |  |  |  |
| Green Force no Smartfit  | 0 | 13.093867  | 27.032994  | 14.601840 |
| Purple Force no Smartfit  |0  | 2.780073  | 16.884920  | 0.184771 |

 **Remark: mass in kg and forces in N.**
_Symmetry among axis_

| Robot  | std (kg) | std no model (kg) |
| ------------- | ------------- | ------------- |
| Green  | 1.098429   | 0.779785  |
| Purple   | 1.392362   | 0.916087 |

Green
![image](https://user-images.githubusercontent.com/11043189/32375596-819083c8-c0a2-11e7-9693-298a1f502d93.png)
Purple
![image](https://user-images.githubusercontent.com/11043189/33017018-00964f8a-cdf1-11e7-86ee-972f611e55bf.png)

 Here it can be compared what the estimation using the model should be against what we are getting from the measurements. The offset has already been substracted

Green
![image](https://user-images.githubusercontent.com/11043189/32375547-568f59b0-c0a2-11e7-9161-c64212521ec6.png)
Purple
![image](https://user-images.githubusercontent.com/11043189/33017267-ffc592e0-cdf1-11e7-80e4-90dfd864084f.png)

**The ideal results should be a shpere close to the one that can be seen in magenta**

Green 
![image](https://user-images.githubusercontent.com/11043189/32375881-8534d49c-c0a3-11e7-8eed-ba33e5e9a7fd.png)
Purple
![image](https://user-images.githubusercontent.com/11043189/33017082-46d7eab2-cdf1-11e7-88d7-8871de0e179a.png)

This can help us see the evolution of the error of the magnitude of the forces along the execution of the grid movements

Remarks: 
Green: Considering the performance of the green iCub while attempting yoga it might be that the left leg sensor is not as bad a as it looks and an exaggeration of the error is induced by the cable being slightly squashed during data collection. Nonetheless it seems the performance is clearly worse than that of the purple.
Purple: The sensors saturate more easily and specially the sensor on the right leg saturated even during the ft check which should not induce high stress on the sensors. Due to this the fitting using the model is not to be trusted and data could be considered corrupted. Even so it gives a bit of insight into the performance of the sensor.

**Comment by fjandrad** [comment]
Comparison was done also with the **new model** for the purple robot.
The differences with this comparison is **negligible. (under 0.01%)**

**Comment by fiorisi** [comment]
@fjandrad the right leg Ft has been replaced (https://github.com/robotology/icub-support/issues/571).
Probably could be interesting to run again your script to evaluate the new sensor. What do you think?

**Comment by fjandrad** [comment]
@fiorisi  we can open a different issue once the sensor is calibrated

**Comment by fjandrad** [comment]
Since we have the comparison results I will close this issue
